name: image_painter
description: A flutter package for drawing over images. Supports color,
  strokeWidth, different paintModes and exporting image.
version: 0.6.1
homepage: https://github.com/yellowQ-software/yellowQ-Flutter-Image-Painter

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.6
  uuid: ^3.0.7
  path_provider: ^2.0.11
  permission_handler: ^10.3.0
  image: ^4.1.3
  resizable_widget:
    git:
      url: https://github.com/zamaniafshar/Flutter-Resizable-Widget.git
      ref: main # branch name